In [1]:
#import the required libraries
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import root_mean_squared_error,mean_absolute_percentage_error,r2_score
from sklearn.ensemble import RandomForestRegressor
import pickle

In [2]:
#Load the fare_pred_model_df
fare_pred_model_df=pd.read_csv(r"D:\VS_CODE\Rapido\drive-download-20260323T152350Z-3-001\cleaned_csv_files\fare_pred_model_df.csv")
fare_pred_model_df.head(2)

,day_of_week,is_weekend,hour_of_day,pickup_location,drop_location,ride_distance_km,estimated_ride_time_min,traffic_level,base_fare,surge_multiplier,...,city_Delhi,city_Hyderabad,city_Mumbai,vehicle_type_Auto,vehicle_type_Bike,vehicle_type_Cab,weather_condition_Clear,weather_condition_Heavy Rain,weather_condition_Rain,booking_value
0,4.0,0,0,19,16,7.01,46.30,2.0,76.12,2.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,148.22
1,1.0,0,6,32,38,9.67,43.54,1.0,254.15,1.8,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,465.85

In [3]:
#check the columns of the df
fare_pred_model_df.columns

Index(['day_of_week', 'is_weekend', 'hour_of_day', 'pickup_location',
       'drop_location', 'ride_distance_km', 'estimated_ride_time_min',
       'traffic_level', 'base_fare', 'surge_multiplier', 'fare_per_km',
       'fare_per_min', 'rush_hour_flag', 'long_distance_flag',
       'city_Bangalore', 'city_Chennai', 'city_Delhi', 'city_Hyderabad',
       'city_Mumbai', 'vehicle_type_Auto', 'vehicle_type_Bike',
       'vehicle_type_Cab', 'weather_condition_Clear',
       'weather_condition_Heavy Rain', 'weather_condition_Rain',
       'booking_value'],
      dtype='object')

In [4]:
#Split the data into input features(X) and the target(y)
X=fare_pred_model_df.drop('booking_value',axis=1)
y=fare_pred_model_df['booking_value']

In [5]:
#split the data into training and testing data
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=47)

In [6]:
#display the X_test values
X_test.head(5)

,day_of_week,is_weekend,hour_of_day,pickup_location,drop_location,ride_distance_km,estimated_ride_time_min,traffic_level,base_fare,surge_multiplier,...,city_Chennai,city_Delhi,city_Hyderabad,city_Mumbai,vehicle_type_Auto,vehicle_type_Bike,vehicle_type_Cab,weather_condition_Clear,weather_condition_Heavy Rain,weather_condition_Rain
93899,1.0,0,22,7,5,13.90,91.76,2.0,206.83,1.4,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
66968,4.0,0,11,39,16,4.36,28.80,2.0,54.91,1.4,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
82817,3.0,0,18,17,25,22.05,99.23,1.0,304.62,1.5,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
23556,1.0,0,12,50,6,6.60,29.69,1.0,198.77,1.2,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
61885,5.0,0,4,24,31,19.67,59.02,0.0,434.14,1.6,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [7]:
X_test.loc[23556]

day_of_week                       1.000000
is_weekend                        0.000000
hour_of_day                      12.000000
pickup_location                  50.000000
drop_location                     6.000000
ride_distance_km                  6.600000
estimated_ride_time_min          29.690000
traffic_level                     1.000000
base_fare                       198.770000
surge_multiplier                  1.200000
fare_per_km                      36.210606
fare_per_min                      8.049512
rush_hour_flag                    0.000000
long_distance_flag                0.000000
city_Bangalore                    0.000000
city_Chennai                      0.000000
city_Delhi                        0.000000
city_Hyderabad                    1.000000
city_Mumbai                       0.000000
vehicle_type_Auto                 0.000000
vehicle_type_Bike                 0.000000
vehicle_type_Cab                  1.000000
weather_condition_Clear           1.000000
weather_condition_Heavy Rain      0.000000
weather_condition_Rain            0.000000
Name: 23556, dtype: float64

In [9]:
X_test.to_csv("X_test_fare_pred_model.csv")

In [8]:
y_test.head(5)

93899    289.26
66968     75.79
82817    443.99
23556    238.99
61885    691.06
Name: booking_value, dtype: float64

In [10]:
y_test.to_csv("y_test_fare_pred_model.csv")

In [12]:
#  x_test and y_test are DataFrames
# Reset index to align rows properly

X_test_reset = X_test.reset_index(drop=True)
y_test_reset = y_test.reset_index(drop=True)

# Concatenate side by side
combined_df = pd.concat([X_test_reset, y_test_reset], axis=1)

# Save to CSV
combined_df.to_csv("x_y_test_combined.csv", index=False)
print(combined_df.head(1))

   day_of_week  is_weekend  hour_of_day  pickup_location  drop_location  \
0          1.0           0           22                7              5

   ride_distance_km  estimated_ride_time_min  traffic_level  base_fare  \
0              13.9                    91.76            2.0     206.83

   surge_multiplier  ...  city_Delhi  city_Hyderabad  city_Mumbai  \
0               1.4  ...         0.0             1.0          0.0

   vehicle_type_Auto  vehicle_type_Bike  vehicle_type_Cab  \
0                1.0                0.0               0.0

   weather_condition_Clear  weather_condition_Heavy Rain  \
0                      1.0                           0.0

   weather_condition_Rain  booking_value
0                     0.0         289.26

[1 rows x 26 columns]

In [13]:
combined_df.to_csv("combined_test_x_y_fare_pred_model.csv")

                              SIMPLE LINEAR REGRESSION MODEL WITH NO FEATURE SELECTION

In [7]:
#Create a model object
model_linear_reg_simple=LinearRegression()
model_linear_reg_simple

LinearRegression()

In [8]:
#Fit the linear regression model

model_linear_reg_simple.fit(X_train,y_train)

LinearRegression()

In [9]:
#Model Prediction
y_pred_train1=model_linear_reg_simple.predict(X_train)
y_pred_test1=model_linear_reg_simple.predict(X_test)

In [10]:
def performance(lab, pred):
    res_lst=[]
    mape = round(mean_absolute_percentage_error(lab, pred)*100,3) 
    rmse = round(root_mean_squared_error(lab, pred),3)
    r2_score_value=round(r2_score(lab,pred),3)
    print("MAPE = ", mape)
    print("RMSE = ",rmse)
    print("R2_score = ",r2_score_value)
    res_lst.append(mape)
    res_lst.append(rmse)
    res_lst.append(r2_score_value)
    return res_lst

In [11]:
#Print the training and test results-MAPE,RMSE,R2_score
print("Training Performance \n")
res_lst_simple_linear_reg_model_train=performance(y_train,y_pred_train1)

print("\nTest Performance \n")
res_lst_simple_linear_reg_model_test=performance(y_test,y_pred_test1)

Training Performance

MAPE =  13.119
RMSE =  37.573
R2_score =  0.967

Test Performance

MAPE =  13.045
RMSE =  37.478
R2_score =  0.967

In [12]:
print(res_lst_simple_linear_reg_model_train)
print(res_lst_simple_linear_reg_model_test)

[13.119, 37.573, 0.967]
[13.045, 37.478, 0.967]

                  FEATURE SELECTION model USING RANDOM FOREST REGRESSOR

In [13]:
#Create the RANDOM FOREST REGRESSOR MODEL OBJECT
fs_model=RandomForestRegressor(random_state=77)
fs_model

RandomForestRegressor(random_state=77)

In [14]:
#Fit the RANDOM FOREST REGRESSOR MODEL
fs_model.fit(X_train,y_train)

RandomForestRegressor(random_state=77)

In [22]:
#Choose the top 10 columns with highest feature importances
selected_columns_df=pd.DataFrame({
    "columns":X_train.columns,
    "score":fs_model.feature_importances_
}).sort_values("score",ascending=False).reset_index(drop=True)

selected_columns_df

                         columns         score
0                      base_fare  8.514909e-01
1               surge_multiplier  1.350070e-01
2                    fare_per_km  5.798150e-03
3               ride_distance_km  3.529269e-03
4        estimated_ride_time_min  2.144190e-03
5                  traffic_level  1.553377e-03
6                   fare_per_min  2.895883e-04
7                pickup_location  4.220373e-05
8                  drop_location  4.047892e-05
9                    hour_of_day  3.185522e-05
10                   day_of_week  2.330387e-05
11                city_Hyderabad  5.736038e-06
12             vehicle_type_Auto  5.680181e-06
13                    city_Delhi  5.570285e-06
14                   city_Mumbai  5.478710e-06
15                  city_Chennai  5.194237e-06
16                city_Bangalore  5.191488e-06
17                    is_weekend  5.056093e-06
18            long_distance_flag  3.141029e-06
19              vehicle_type_Cab  2.532545e-06
20                rush_hour_flag  1.656753e-06
21        weather_condition_Rain  1.537741e-06
22             vehicle_type_Bike  1.123239e-06
23  weather_condition_Heavy Rain  1.027989e-06
24       weather_condition_Clear  8.227467e-07

None of the columns omitted as the categorical columns are at the end too.

                              RANDOM FOREST REGRESSOR MODEL

In [23]:
random_forest_model=RandomForestRegressor(n_estimators= 300, random_state= 88, max_depth= 10)
random_forest_model

RandomForestRegressor(max_depth=10, n_estimators=300, random_state=88)

In [24]:
random_forest_model.fit(X_train,y_train)

RandomForestRegressor(max_depth=10, n_estimators=300, random_state=88)

In [25]:
y_pred_train2=random_forest_model.predict(X_train)
y_pred_test2=random_forest_model.predict(X_test)

In [26]:
print("Training Performance\n")
res_lst_random_forest_train=performance(y_train,y_pred_train2)

print("\nTesing Performance\n")
res_lst_random_forest_test=performance(y_test,y_pred_test2)

Training Performance

MAPE =  1.932
RMSE =  7.21
R2_score =  0.999

Tesing Performance

MAPE =  2.052
RMSE =  7.724
R2_score =  0.999

In [27]:
print(res_lst_random_forest_train)
print(res_lst_random_forest_test)

[1.932, 7.21, 0.999]
[2.052, 7.724, 0.999]

In [28]:
res_df = pd.DataFrame(
    [
        res_lst_simple_linear_reg_model_train,
        res_lst_simple_linear_reg_model_test,
                
        res_lst_random_forest_train,
        res_lst_random_forest_test
    ],
    index=["LINER_REG_TRAIN","LINEAR_REG_TEST","RANDOM_FOREST_TRAIN","RANDOM_FOREST_TEST"],
    columns=["RMSE","MAPE","R2_SCORE"]
)

print(res_df)

                       RMSE    MAPE  R2_SCORE
LINER_REG_TRAIN      13.119  37.573     0.967
LINEAR_REG_TEST      13.045  37.478     0.967
RANDOM_FOREST_TRAIN   1.932   7.210     0.999
RANDOM_FOREST_TEST    2.052   7.724     0.999

The Random Forest model achieves near-perfect predictive accuracy (R² ≈ 0.999) with minimal error margins, outperforming baseline linear regression by an order of magnitude. This ensures highly reliable predictions in production
So The Random Forest model can be used for testing in STREAMLIT DASHBOARD

In [34]:

# Save the RF model using pickle
filename = "RF_model.pkl"
model=random_forest_model

# Save the model to disk
with open(filename, "wb") as file:
    pickle.dump(model, file)

print("Model saved successfully!")

Model saved successfully!